name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with your repository's main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      run: |
        git checkout main
        git push origin main:gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

